### ISSUE TITLE
How to stream to rtmp server, e.g. rtmp://localhost:5000

### ISSUE THREAD

**Issue by najeeb-tyson** [madams1337/python-opencv-gstreamer-examples#1]
I have a nginx server running which accepts stream with _rtmp_ protocol. I want to modify the file [https://github.com/madams1337/python-opencv-gstreamer-examples/blob/master/gst_device_to_rtp.py](url) . Can you help me with this.

**Comment by mad4ms** [comment]
Hey,

currently, i don't have a nginx server to test it with, but i guess if you change the line #17 in the file from
`gst_str_rtp = "appsrc ! videoconvert ! x264enc tune=zerolatency bitrate=500 speed-preset=superfast ! rtph264pay ! udpsink host=127.0.0.1 port=5000`

to something like

``gst_str_rtp = "appsrc ! videoconvert ! x264enc tune=zerolatency bitrate=500 speed-preset=superfast ! rtph264pay ! rtmpsink location=\"rtmp://localhost/YOURAPP/YOURSTREAM\"``

whereas you need to adapt YOURAPP and YOURSTREAM to your according needs.

I also found some articles on how to do this:

[1] https://stackoverflow.com/questions/26490164/gstreamer-streaming-to-nginx-rtmp-server
[2] https://www.sk89q.com/2014/05/broadcasting-a-video-playlist-to-nginx-rtmp-module/
[3] http://nginx-rtmp.blogspot.com/2013/07/gstreamer-and-raspberry-pi.html

Hope this helps!

Best,
M

**Comment by najeeb-tyson** [comment]
Thanks

**Comment by zjd1988** [comment]
Hi @najeeb-tyson ，did this worked for you
