### ISSUE TITLE
Betrayal

### ISSUE THREAD

**Issue by git-hamza** [madams1337/python-opencv-gstreamer-examples#11]
Did I really get rickrolled on GitHub? This was the last place I was expecting to get rickrolled, my day is ruined and my disappointment is immeasurable.

P.S. Good One though

**Comment by mad4ms** [comment]
> Did I really get rickrolled on GitHub? 

First time? Have a look at this [repo](https://bitly.com/98K8eH), way better actually!

>This was the last place I was expecting to get rickrolled, my day is ruined and my disappointment is immeasurable.

I'm sorry :(

> P.S. Good One though

Thank you :)

**Comment by git-hamza** [comment]
Are you kidding me? again. I surely will have trust issues from now on. You are a madman

![memee](https://user-images.githubusercontent.com/55538578/202662208-918a94b6-e403-42c0-be9f-eaa2fb180d73.jpg)
