### ISSUE TITLE
Can GStreamer running without GPU?

### ISSUE THREAD

**Issue by htaufik** [madams1337/python-opencv-gstreamer-examples#3]
Hello, can your code and gstreamer work without gpu?

**Comment by mad4ms** [comment]
Sure!

Everything that has no Intel or Nvidia in it runs on the CPU.
E.g. `x264enc` solely runs on CPU, while `mfxh264enc ` and the not yet existing Nvidia examples run on Intel or Nvidia GPU, respectively.

**Comment by htaufik** [comment]
ok, gonna try it.. thanks before

**Comment by htaufik** [comment]
hello, can i ask something?
i'm trying to implement how you capture and show the output to my code. my source stream is from rtsp camera, when i run the code, the frame window can show the output, but the rtp didn't show and just loading (i'm using vlc). do you have any solution?

**Comment by mad4ms** [comment]
> hello, can i ask something?

Sure ;).

> i'm trying to implement how you capture and show the output to my code. my source stream is from rtsp camera, when i run the code, the frame window can show the output, but the rtp didn't show and just loading (i'm using vlc). do you have any solution?

Did you utilize the stream_localhost.sdp file? VLC needs an sdp file in order to get access to an rtp file. Just edit the file according to your needs (e.g. adapt the IP address if you use it from a different PC than localhost) and open it in VLC.

Also you can inspect the VLC debug output to see what's missing. Or you can share your gstreamer here so that i can have a closer look.

**Comment by htaufik** [comment]
how to open sdp files in vlc? sorry i'm new here  :"D
this is my code for input and output, the entire code is for my face recognition
```
#initialize the camera
cap = cv2.VideoCapture("rtsp://192.168.150.79:11083")
gst_str_rtp = "appsrc ! videoconvert ! x264enc tune=zerolatency bitrate=500 speed-preset=superfast ! rtph264pay ! udpsink host=192.168.150.79 port=11083"
out = cv2.VideoWriter(gst_str_rtp, 0, 30, (640, 480), True)
```
this is my sdp file
```
c=IN IP4 192.168.200.99 //(my computer ip)
m=video 5004 RTP/AVP 96
a=rtpmap:96 H264/90000
```
is this correct?

**Comment by mad4ms** [comment]
> how to open sdp files in vlc? sorry i'm new here :"D

You can simply click "open" and select the file in vlc. Or `Ctrl + O` opens the dialog as well, then simply select the file.

> this is my code for input and output, the entire code is for my face recognition
> 
> ```
> #initialize the camera
> cap = cv2.VideoCapture("rtsp://192.168.150.79:11083")
> gst_str_rtp = "appsrc ! videoconvert ! x264enc tune=zerolatency bitrate=500 speed-preset=superfast ! rtph264pay ! udpsink host=192.168.150.79 port=11083"
> out = cv2.VideoWriter(gst_str_rtp, 0, 30, (640, 480), True)
> ```

The string is correct, the openCV code as well.

> 
> this is my sdp file
> 
> ```
> c=IN IP4 192.168.200.99 //(my computer ip)
> m=video 5004 RTP/AVP 96
> a=rtpmap:96 H264/90000
> ```
> 
> is this correct?

Not entirely. Two things:
1.) `host=192.168.**150**.79 port=11083` in the gst_str_rtp is in a different subnet than your computer ip (`192.168.**200**.99`) in the sdp file. That may cause difficulties. 
2.) The port is not correct. In the gst_str_rtp, you have selected `port=11083`, while in the sdp file, the "usual" port of rtp streams is selected `m=video **5004** RTP/AVP 96` (highlighted with **). These two numbers need to be the same.

I'm not 100% sure if 1.) could cause problems, so start with adapting the port number to e.g. 5004 and try again.

**Comment by htaufik** [comment]
so in variable `gst_str_rtp` i must call my computer IP not my camera IP? and the port it should be `5004`? am i right?

**Comment by htaufik** [comment]
I've changed the port number to `5004` in gst_str_rtp and sdp file, but still can't get the output.. I get an error message in VLC `live555 error: no data received in 10s, aborting`

**Comment by htaufik** [comment]
> Not entirely. Two things:
> 1.) `host=192.168.**150**.79 port=11083` in the gst_str_rtp is in a different subnet than your computer ip (`192.168.**200**.99`) in the sdp file. That may cause difficulties.

I've changed my ip and port in gst_str_rtp same as my computer ip with `5004` as port. But, VLC still get a mesage `live555 error: no data received in 10s, aborting`. What should i do?

**Comment by htaufik** [comment]
Or maybe because the segment in my computer IP and my Camera not same?

**Comment by mad4ms** [comment]
> Or maybe because the segment in my computer IP and my Camera not same?

That's probably it. Can you ping the other PC / camera? I currently don't have the possibility to test your setup.
Do you have a firewall that's maybe blocking these ports?

**Comment by htaufik** [comment]
> > Or maybe because the segment in my computer IP and my Camera not same?
> 
> That's probably it. Can you ping the other PC / camera? I currently don't have the possibility to test your setup.

I can ping my camera. And if try to change the segment, my camera become offline, also if i change my vm segment it can't access network..

> Do you have a firewall that's maybe blocking these ports?

I'm using netcat to check it , and connection failed to my camera with port `5004`, if i changed to my camera with rtsp port `11083` the result is success. Is this a sign that port `5004` is blocked?

**Comment by htaufik** [comment]
What if i try my output to become rtsp not rtp, is it possible?

**Comment by mad4ms** [comment]
It seems like your camera is streaming its data at port 11083. That explains why you can netcat it and it connects. If you try to ping your camera on port 5004, it won't answer since you have no service running on your camera providing that port.

That means that you can leave the VideoCapture object the way it is with the port 11083.
Your gst pipe
`gst_str_rtp = "appsrc ! videoconvert ! x264enc tune=zerolatency bitrate=500 speed-preset=superfast ! rtph264pay ! udpsink host=192.168.150.79 port=11083"
`
tries to write the RTP stream back to your camera, which probably won't work out. Change the host to your local pc ip 192.168.200.99 and set the port to 5004 like that:
`gst_str_rtp = "appsrc ! videoconvert ! x264enc tune=zerolatency bitrate=500 speed-preset=superfast ! rtph264pay ! udpsink host=192.168.200.99 port=5004"
`
and try the SDP file with the following content:
`
c=IN IP4 192.168.200.99 //(my computer ip)
m=video 5004 RTP/AVP 96
a=rtpmap:96 H264/90000
`

**Comment by mad4ms** [comment]
> What if i try my output to become rtsp not rtp, is it possible?

It won't require an sdp file then, but the setup is quite more complicated. You can have a look at the example in this very repo on how to setup an RTSP stream, although it is an quite old example and i cannot guarantee that it will work 100%.

**Comment by htaufik** [comment]
> `gst_str_rtp = "appsrc ! videoconvert ! x264enc tune=zerolatency bitrate=500 speed-preset=superfast ! rtph264pay ! udpsink host=192.168.200.99 port=5004" `
> and try the SDP file with the following content:
> `c=IN IP4 192.168.200.99 //(my computer ip) m=video 5004 RTP/AVP 96 a=rtpmap:96 H264/90000`

I have try this on your repo, but still can't see  the output in vlc...

**Comment by mad4ms** [comment]
> > `gst_str_rtp = "appsrc ! videoconvert ! x264enc tune=zerolatency bitrate=500 speed-preset=superfast ! rtph264pay ! udpsink host=192.168.200.99 port=5004" `
> > and try the SDP file with the following content:
> > `c=IN IP4 192.168.200.99 //(my computer ip) m=video 5004 RTP/AVP 96 a=rtpmap:96 H264/90000`
> 
> I have try this on your repo, but still can't see the output in vlc...

Dang. Ok, you can also try to change both your IP adresses to the localhost address "127.0.0.1" as in the example file. Maybe there's a firewall / router problem.

`gst_str_rtp = "appsrc ! videoconvert ! x264enc tune=zerolatency bitrate=500 speed-preset=superfast ! rtph264pay ! udpsink host=127.0.0.1 port=5004" `

and

c=IN IP4 127.0.0.1 //(my computer ip) m=video 5004 RTP/AVP 96 a=rtpmap:96 H264/90000

Also if you work with linux, you can type `export GST_DEBUG=4` (in the same terminal your exec'ing your streaming python script) to have an extensive debug output of gstreamer. You can look for warnings and errors in this output,

**Comment by htaufik** [comment]
> `gst_str_rtp = "appsrc ! videoconvert ! x264enc tune=zerolatency bitrate=500 speed-preset=superfast ! rtph264pay ! udpsink host=127.0.0.1 port=5004" `
> and
> c=IN IP4 127.0.0.1 //(my computer ip) m=video 5004 RTP/AVP 96 a=rtpmap:96 H264/90000

still can't work :"(

> Also if you work with linux, you can type `export GST_DEBUG=4` (in the same terminal your exec'ing your streaming python script) to have an extensive debug output of gstreamer. You can look for warnings and errors in this output,

when i type `export GST_DEBUG=4` before i run the program, it not show warnings or errors

**Comment by mad4ms** [comment]
Did you try again? Any success?

**Comment by htaufik** [comment]
Still can't work
