### ISSUE TITLE
Where do we stream voice ?

### ISSUE THREAD

**Issue by thusinh1969** [madams1337/python-opencv-gstreamer-examples#6]
Hi,

I do not see any example that can stream full video + voice/music channel? Can someone help?

Thanks,
Steve

**Comment by mad4ms** [comment]
As I don't aim for streaming audio data along with video, there's no example for that provided.

There are plenty of ressources on how to stream video and audio together, the easiest to understand seems to be this one:
[4youngpadawans](http://4youngpadawans.com/gstreamer-real-life-examples/)
