### ISSUE TITLE
gst_device_to_shm.py  is not Working

### ISSUE THREAD

**Issue by BestITUserEUW** [madams1337/python-opencv-gstreamer-examples#8]
Hey im trying to  use gst_device_to_shm.py Example to write to shared Memory. But your Example is not writing it to shared Memory. When i try running it with Gstreamer:
`gst-launch-1.0 appsrc ! videoconvert ! shmsink socket-path=/tmp/foo sync=true wait-for-connection=false shm-size=10000000`
it works fine. Do you have any advice also giving the Script Permissions with: 
`chmod +x myScript.py` 
doesn't work.

**Comment by mad4ms** [comment]
Hey,

a few things to check here:
1. Did you adjust the camera parameters to your webcam? Maybe you can try it with a lower resolution that suits your webcam (e.g. 640x480 and lower fps)
2. Check if there's a handle "foo" in the folder `/tmp`. Delete it manually if it remains in the folder after terminating the script.
3. Unlikely that is has something to do with permissions

Let me know if this helps.

**Comment by BestITUserEUW** [comment]
Thanks for your fast reply 
1. Tried adjusting cam parameters and lower fps
2. Theres no handle foo created in the tmp dir 
Could it maybe be a Version thing ?
cv2 = opencv-python   4.5.5.62
Gstreamer = gstreamer1.0

**Comment by mad4ms** [comment]
Thanks for trying. 

Did you compile OpenCV with GStreamer support?
 If not, have a look at the tutorial in the README.

**Comment by BestITUserEUW** [comment]
Did not see that, thought that normal opencv from pip was enough. Ill do it now. 
Thank you for your time.
