### ISSUE TITLE
Question: about gst_shm_to_app.py !appsink

### ISSUE THREAD

**Issue by BestITUserEUW** [madams1337/python-opencv-gstreamer-examples#9]
Hello,
i am using your gst_device_to_shm.py Example for writing cv2 to shared memory. On the other side i acces the shared memory source with.
`gst-launch-1.0 --gst-debug-level=2 -v shmsrc socket-path=/tmp/foo ! video/x-raw,format=BGR,width=640,height=512,framerate=30/1 ! decodebin ! videoconvert ! x264enc bframes=0 key-int-max=45 bitrate=512 tune=zerolatency ! video/x-h264,profile=baseline,stream-format=avc,alignment=au ! kvssink stream-name="mystream" storage-size=128 access-key="my_key" secret-key="my_key" aws-region="my_region"
` 
but i cant use the appsink with h264 enc. Its working most likely fine but it has Problems with Fragments on the KVS site.
So my Question is what exactly is the appsink at the end doing. Thanks in Advance

**Comment by mad4ms** [comment]
Hi,

in the `gst_shm_to_app.py`, the appsink element in the GStreamer pipeline enables OpenCV's videoreader to access the images acquired in this pipeline. I barely use the appsrc/appsink elements outside python code.

Furthermore:
according to [the doc](https://gstreamer.freedesktop.org/documentation/tutorials/basic/short-cutting-the-pipeline.html?gi-language=c): 

> The element used to inject application data into a GStreamer pipeline is appsrc, and its counterpart, used to extract GStreamer data back to the application is appsink

Please close the issue if you're good with the answer ;).
